channels:
  - pytorch
  - conda-forge
  - rdkit
  - pyg

dependencies:
  - python=3.9
  - sphinx-autoapi
  - pytorch=1.11.0
  - conda-forge::rdkit=2022.03.5
  - matplotlib==3.6.0
  - numpy=1.23.3
  - pandas=1.5.0
  - tqdm=4.64.1
  - scipy=1.9.1
  - pip=22.2.2
  - cython=0.29.32
  - scikit-learn=1.1.2
  - seaborn=0.12.0
  - click=8.1.3
  - pytest=7.1.3
  - pip:
      - pyyaml==6.0
      - pyarrow==9.0.0
      - ruffus==2.8.4
      - networkx==2.8.8
      - git+https://github.com/thejonaslab/tinygraph.git
      - scikit-spatial==6.5.0
      - tensorboardx==2.5.1
      - sqlitedict==2.0.0
      - pot==0.8.2
      - sqlalchemy==1.4.45
